name: hello_workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step with a secret
        run: |
          echo "Secret testing:"
          echo "This is a secret value: ${{ secrets.SECRET_VALUE }}"
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world using echo
        run: echo "$(<hello.txt)"
      - name: Hello world using cat
        run: cat hello.txt
  show-secret-phrase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: abystoma/test
          ref: main
      - name: Show me the answer
        run: cat answer.txt
